### ISSUE TITLE
Add Explore Nested Layout in SubPages: Comics, Offers, Collectors

### ISSUE THREAD

**Issue by Pearlsky** [chingu-voyages/v43-tier3-team-36#89] opened 2023-03-30 23:03 UTC
**__Task Description__**
I reasoned that it is not optimal to render separate **tab menus** across the various subpages (comics, offers, collectors) on the explore page. Since @TazDeCoder already did good on the `ExploreNavbar` component, this component can be rendered in a `layout.tsx` (could be named `ExploreLayout`) and this layout wrapped around each explore subpage. 

The layout would never re-ender while switching between the various explore subpages. (I've tried and tested this and it works okay, and i'd like to commit the code for you guys to see)
cc: @TazDeCoder @fmtabbara

**Comment by TazDeCoder** [comment] 2023-03-30 23:19
@Pearlsky that's great that you were able to find a way to refactor this, but the `Layout.tsx` file isn't what we want to base our page layouts on - we want to be based of the `AuthLayout.tsx`.

So here what you will need to do:
- Create the `ExploreLayout.tsx` just like the `Layout.tsx` with the component from the`ExploreNavbar` - create a duplicate of this same exact component inside of it and call it `Navbar`
- Move the `Navigation` component inside of `AuthLayout.tsx` and **into the `components/common` folder**
- Import the `Navigation` component in both the `AuthLayou.tsx` and `ExploreLayout.tsx` layoyts
- Finally, remove the `ExploreNavbar` from the `components/explore` folder and all its instances from the `pages` folder

If you struggle to follow through what is being said, then feel free to reach out

**Closed** 2023-03-31 09:58 UTC
Labels: task, fe, update
